[jobs.run]
command = [
    "cargo", "run", "--target", "x86_64-pc-windows-gnu",
    "--color", "always",
    # put launch parameters for your program behind a `--` separator
]
need_stdout = true
allow_warnings = true

background = false
on_change_strategy = "kill_then_restart"